alter table car drop foreign key FKbp2cjm2fx85d538siqn09ubsd;
alter table car drop foreign key FKgfht1l5lcn8gbugha10mnt4bg;
alter table car drop foreign key FKchdpe924jrjx3mbgtcod0amcg;
alter table car_model drop foreign key FK39nh3m4918h84h2rcnaf14x02;
drop table if exists car;
drop table if exists car_class;
drop table if exists car_model;
drop table if exists fuel_type;
drop table if exists producer;
alter table car drop foreign key FKbp2cjm2fx85d538siqn09ubsd;
alter table car drop foreign key FKgfht1l5lcn8gbugha10mnt4bg;
alter table car drop foreign key FKchdpe924jrjx3mbgtcod0amcg;
alter table car_model drop foreign key FK39nh3m4918h84h2rcnaf14x02;
drop table if exists car;
drop table if exists car_class;
drop table if exists car_model;
drop table if exists fuel_type;
drop table if exists producer;
alter table car drop foreign key FKbp2cjm2fx85d538siqn09ubsd;
alter table car drop foreign key FKgfht1l5lcn8gbugha10mnt4bg;
alter table car drop foreign key FKchdpe924jrjx3mbgtcod0amcg;
alter table car_model drop foreign key FK39nh3m4918h84h2rcnaf14x02;
drop table if exists car;
drop table if exists car_class;
drop table if exists car_model;
drop table if exists fuel_type;
drop table if exists producer;
